DISCLAIMERS = {
    "reviewer": (
        "DISCLAIMER: This report was generated by an automated AI review assistant. "
        "It is intended to help the review committee quickly identify structural flaws, missing baselines, "
        "and track alignment issues. It is NOT a substitute for rigorous human peer review.\n\n"
        "KNOWN LIMITATIONS:\n"
        "1. Figures, tables, and complex diagrams are NOT analyzed by the AI and must be checked manually.\n"
        "2. Deep mathematical proofs and specialized factual claims are not fully verified.\n"
        "3. Use this as a preliminary screening tool to guide your manual evaluation."
    ),
    "author": (
        "DISCLAIMER: This report provides automated preliminary feedback to help you refine "
        "your manuscript prior to full peer review. The recommendations provided are constructive suggestions "
        "based on structural pattern recognition.\n\n"
        "KNOWN LIMITATIONS:\n"
        "1. Figures, tables, and complex diagrams are NOT analyzed by the AI.\n"
        "2. Deep mathematical proofs and specialized factual claims are not verified.\n"
        "3. Please use your independent academic judgment when applying this feedback to improve your paper."
    )
}