
DISCLAIMER_TEXT = (
    "DISCLAIMER: This report was generated by an automated AI review assistant. "
    "It is intended to provide preliminary feedback on structure, completeness, and track alignment. "
    "KNOWN LIMITATIONS:\n"
    "1. Figures, tables, and complex diagrams are NOT analyzed by the AI\n"
    "2. Deep mathematical proofs, complex equations, and highly specialized factual claims may not be fully verified.\n"
    "3. The recommendations provided are suggestions based on structural pattern recognition. "
)